version: '2'

services:
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./containers/nginx/silex.conf:/etc/nginx/conf.d/silex.conf
    volumes_from:
      - app
  php:
    image: php:7-fpm
    expose:
      - "9000"
    volumes_from:
      - app
  app:
    image: debian:jessie
    volumes:
      - ./containers/app:/var/www
