version: '2'

services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    environment:
      SSH_KEY: ''
      GIT_REPO: 'git@github.com:wbits/kxb.git'
      GIT_EMAIL: ''
      GIT_NAME: 'wbits'
