version: '2'

services:
  pgsql:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  phpfpm:
    image: php:7-fpm
    expose:
      - "9000"
    volumes:
      - /var/www/app
    links:
      - pgsql
  nginx:
    build: ./nginx
    ports:
      - "80"
    links:
      - phpfpm
    volumes:
      - ./docker/nginx/silex.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - phpfpm
