version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/silex
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm

  fpm:
    build: docker/php-fpm/
    volumes:
      - ./:/var/www/silex
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - db

  db:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - 5432:5432
    environment:
      - DB_USER=kxbusr
      - DB_PASS=kxbpss
      - DB_NAME=kxb
#    volumes:
#      - ./docker/postgresql:/var/lib/postgresql
